#!/usr/bin/env python
import cv2
import numpy as np
import sys

cam=cv2.VideoCapture(0)

if not cam.isOpened():
  print >> sys.stderr,'error: uvc camera can not open'
  sys.exit(1)

cnt=0
while(True):
  r,i=cam.read()
  if r:
    cv2.imshow('video',i)
    k = cv2.waitKey(10)
    if k == 99:	# key of 'c'
      cv2.imwrite('%10d'%(cnt)+'.jpg',i)
      print('camera captured in %10d.jpg'%(cnt))
      cnt+=1
    if k==27:break
  else:
    print >> sys.stderr,'error: uvc camera not ready to use'
    break
cam.release()
